name: 01 - Building Blocks

on: push
on: workflow_dispatch

jobs:
  echo-hello:
    runs_on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "I will fail"
          exit 1
      - name: Say goodbye
        run: echo "Goodbye!"