name: 03 - Workflow Runners

on: workflow_dispatch

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on an Ubuntu runner."
                echo ${{ github.runner }}
    ubuntu-window:
        runs-on: windows-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on a Windows runner."
                echo $RUNNER_OS
    mac-window:
        runs-on: mac-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on a MacOS runner."
                echo ${{ github.runner }}